# Generated by Django 5.0.3 on 2024-05-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
