# Generated by Django 5.0.3 on 2024-05-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0005_progress_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('urls_material', models.TextField(help_text='Ingresa los URLs del material, separados por comas.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.activity')),
            ],
        ),
    ]
