# Generated by Django 5.0.3 on 2024-03-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0005_remove_activity_score_remove_pregunta_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='puntaje_obtenido',
        ),
        migrations.AddField(
            model_name='activity',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.activity'),
        ),
    ]
