# Generated by Django 5.0.3 on 2024-03-19 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0006_remove_activity_puntaje_obtenido_activity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestausuario',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.activity'),
        ),
    ]
