# Generated by Django 5.0.3 on 2024-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0007_respuestausuario_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='areas_mejora',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nivel_idioma',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default=None, max_length=20, null=True),
        ),
    ]
