# Generated by Django 5.0.3 on 2024-03-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0008_remove_student_age_student_areas_mejora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestausuario',
            name='activity',
        ),
    ]
