# Generated by Django 5.0.3 on 2024-03-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0010_respuestausuario_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
