# Generated by Django 5.0.3 on 2024-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0013_remove_respuestausuario_puntaje_obtenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='score',
        ),
        migrations.AddField(
            model_name='respuestausuario',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
